# Conda environment configuration for the ML for Biomedicine Streamlit app
name: streamlit_app_mlbm
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.9
  - streamlit=1.29.0
  - pandas>=2.0.0
  - numpy>=1.24.0
  - torch>=2.0.0
  - spacy=3.7.2
  - sentence-transformers=2.2.2
  - nltk=3.8.1
  - plotly=5.15.0
  - matplotlib=3.7.1
  - seaborn=0.12.2
  - scikit-learn=1.3.0
  - wordcloud=1.9.2
  - pyyaml=6.0
  - joblib=1.3.2
  - imageio=2.31.1
  - pip
  - pip:
      - en-core-web-sm==3.7.2